name: Build and Deploy to NCP
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # 수동 실행 트리거 추가

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 체크아웃 및 JDK 세팅
    - name : Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    # Aplication YML 파일 생성
    - name: Make application.yml
      run: |
        mkdir -p src/main/resources
        echo "${{ secrets.APPLICATION_AUTH_YML }}" | base64 --decode > src/main/resources/application-auth.yml
        echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
        find src
      shell: bash
    # Gradle 권한 부여
    - name: Grant permission for gradlew
      run: chmod +x ./gradlew
    # 빌드
    - name: Build with Gradle
      run: ./gradlew clean build
    #빌드한 jar 파일을 도커 이미지로 빌드하고 도커 허브에 푸시
    - name: web docker build and push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dive-in .
        docker push ${{ secrets.DOCKER_USERNAME }}/dive-in
  deploy:
    # needs를 통해 build job이 수행 성공시에 작업되도록 설정
    needs: build
    runs-on: ubuntu-latest
    steps:
    # NCP 로그인 / docker image pull & run
    - name: NCP login and docker image pull and run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.NCP_HOST }}
        username: ${{ secrets.NCP_USERNAME }}
        password: ${{ secrets.NCP_PASSWORD }}
        port: ${{ secrets.NCP_PORT }}
        script: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker network create web-network || true
          sudo docker stop diveincontainer
          sudo docker rm -f diveincontainer
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/dive-in
          sudo docker run -d -p 8080:8080 --network web-network --name diveincontainer ${{ secrets.DOCKER_USERNAME }}/dive-in
